resources:
  - url: http://127.0.0.1:5000/media-card.js
    type: module
views:
  - cards:
      - type: custom:media-card
        name: Media Card Development
        entity: sun.sun
        test_gui: true
